### ISSUE TITLE
if it will display the whole size by click,i think it's perfect.

### ISSUE THREAD

**Issue by zhendong590** [Pixabay/jQuery-flexImages#10]
this plugin's style is very good for me .i like it very much .if it will display the whole size by click,like image zoom or image viewer, i think it's perfect.

**Comment by SimonSteinberger** [comment]
You can do any action you like on clicking the images. E.g. you can use a lightbox plugin to zoom them. Or if you take a look at Pixabay.com, you'll see an enlarged preview image on hover: http://pixabay.com/en/photos/?order=best So, it's all up to you. Click on Pixabay leads to the appropriate details pages.

**Comment by zhendong590** [comment]
thank you i will try
