### ISSUE TITLE
More of a question then issue - full screen calculation..

### ISSUE THREAD

**Issue by webdpro** [Pixabay/jQuery-flexImages#11]
Is it possible to have the flexImages plugin calculate and force the images to cover the screen? So what I'm running into is that if there are not enough images there will be a gap at the bottom of the screen, I know I could just add another row of images but was wondering if there was a setting that could just calculate the container size, see if there is a gap then adjust accordingly to fill the gap by increasing the image sizes? 

Anyhow just an idea Thanks!

**Comment by SimonSteinberger** [comment]
No, not possible. But that's what the truncate option is for. Otherwise the last row's image(s) coudl get incredibly large.
