### ISSUE TITLE
Incorrect width using Bootstrap 3

### ISSUE THREAD

**Issue by velizarov** [Pixabay/jQuery-flexImages#15]
It is help me. I have changed the file jquery.flex-images.js
```javascript
new_w = Math.ceil(row[x][2]*ratio)-2;
```
instead of 
```javascript
new_w = Math.ceil(row[x][2]*ratio);
```
**The example**
http://www.prof-restavrazia.ru/gallery

**Comment by velizarov** [comment]
Looks like the root cause is not in Bootstrap.
It is Chrome - the known issue https://github.com/Pixabay/jQuery-flexImages/issues/9

**Comment by SimonSteinberger** [comment]
Thanks, I'll test a bit and include the fix then. Is "-2" required, or may "-1" be enough to fix the issue? I'm not seeing it on my system, so I cannot test it.

Best, Simon

**Comment by velizarov** [comment]
Hi Simon,

"-1" was not enough to fix. I tested it.

BR,
Vladimir

**Comment by SimonSteinberger** [comment]
Thanks velizarov for bringing this to our attention! I cannot reproduce the issue, but from what I read, I guess reducing the size in a different spot as suggested in #9 is probably a slightly better approach. Does the recent change work for you?

**Comment by velizarov** [comment]
I will check and let you know.
