### ISSUE TITLE
Centre alignemt causes resize bug, gets smaller and smaller till images dispear 

### ISSUE THREAD

**Issue by x00** [Pixabay/jQuery-flexImages#17]
In mobile devices when you scroll up the address bar appears. This resizes the page. With centre alignment the images get progressively smaller, until they disappear. This doesn't happen very fast on mobile device, but the margin from the sides increase as the images get smaller and also if there is row limit/truncate images disappear/drop off the end never to reappear. 

A fast way of testing this is in desktop is by rapidly expanding and contracting the size the browser window, in height and width. 

Bellow is example code of the alignment. 

``` html
<div class="wrapper">
    <div class="container">
        <div class="imgFiles">
            <div class="item" data-w="600" data-h="400"><img src="/path/to/some/img.jpg" alt="someimg"></div>
            <div class="item" data-w="600" data-h="400"><img src="/path/to/some/img.jpg" alt="someimg"></div>
            <div class="item" data-w="600" data-h="400"><img src="/path/to/some/img.jpg" alt="someimg"></div>
        </div>
    </div>
</div>

<style>
.wrapper {
    text-align: center;
}

.container {
    display: inline-block;
}
</style>

<script>
    jQuery('.imgFiles').flexImages({rowHeight: 250, maxRows: 1});
</script>
```

**Comment by SimonSteinberger** [comment]
That's weird. Shouldn't the address bar appear _over_ the page content. I never realized it has any influence on the content's height/width.

**Comment by x00** [comment]
it creates a resize event Andriod, and iOS.

It is not over, or else the top of the page would be cut off. 

Even the keyboard has effect on position: fixed.

**Comment by x00** [comment]
like I say its a problem in desktop too becuase windows are resized.

**Comment by SimonSteinberger** [comment]
Looks like nobody can confirm this issue and I don't see this behavior on my systems.
