### ISSUE TITLE
Force row height

### ISSUE THREAD

**Issue by rctneil** [Pixabay/jQuery-flexImages#18]
Is there an option where the row height could be forced and item contents (images) could do one of two things:
- Fit in the box so every pixel is visible

OR
- Use an object-fit style method to ensure that the item is covered by the image in some way.

I look forward to hearing.

**Comment by SimonSteinberger** [comment]
I don't fully understand - possibly. But you can just play around with CSS properties if you place the images inside container DIVS. But I don't think this would be very cross-browser safe. Tempering with the object aligning algorithm itself and calculating required image dimensions will likely be complex.

**Comment by rctneil** [comment]
The problem I have that created this issue is that I have started to integrate fleximages with MixItUp. It's working but with a few issues and caveats:
- Each time a MixItUp filter button is clicked, before MixItUpStarts I ensure all items have a `.flex-item` class. I then allow MixItUp to do it's filtering and using the end callback it provides I remove the `.flex-item` class from any `.flex-item`'s that are set to `display: none` and rerun fleximages.    The issue is that, because each line of flex items are NOT the same height, when items from differing rows get placed on the same row due to filtering then once MixItUp is finished and fleximages reruns it's does a slight jump and stutters as it fits the height of the elements to flush align the right edges on the right side of the container.

Any thoughts on a way to solve this?

**Comment by SimonSteinberger** [comment]
As I see it, that's a totally different behavior than what the plugin currently does. I see no way of including this as an option in a reasonable way.
