### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by rootsup** [Pixabay/jQuery-flexImages#3]
Images stretching and cropping strange on iOS devices, and occasionaly in safari for osx

**Comment by SimonSteinberger** [comment]
That's not helpful. Can you provide at least a screenshot of the issue?

**Comment by rootsup** [comment]
Sorry about the repost. Didn't realize. 
This seems to be an issue with safari mainly. All iOS devices exhibit it, and safari on osx does occasionally. I'll hook up the dev console to my phone later today and report back

**Comment by SimonSteinberger** [comment]
Hm, unfortunately, I don't have an Apple device for testing here. Also, I really don#t see the bug in your screenshot above. It looks normal to me ...

**Comment by rootsup** [comment]
Look at the eagle, It's stretched long. In hooking up my phone I've discovered it's a draw issue with .fleximages .item img{width:auto;} which safari doesn't seem to like. I found that when shut off and turned back on it seems to draw correctly, so I'm attempting a small in page script to do so.

**Comment by SimonSteinberger** [comment]
Ahhh - I see :) Thanks!

Maybe it helps adding a "display: block" or "display: inline-block" to the image's CSS. Could you try that? I'd liek to help, but can't see the bug here on my test browsers.

**Comment by rootsup** [comment]
YES! Thank you so much. Wayy easier than writing a script to change it all!
     // .flex-images .item img {width:auto; height:100%; display:block;}
Possibly add that to the master css file here?

**Comment by SimonSteinberger** [comment]
Will do that tonight :-) Thanks for testing!
